swagger: '2.0'
info:
  title: Tiyaro
  version: '1.0'
host: api.tiyaro.ai
basePath: /
schemes:
  - https
paths:
  /model_specific_path:
    parameters:
      - description: 'Available service tiers: [cpuflex(default), gpuflex]'
        in: query
        name: serviceTier
        required: false
        type: string
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/ImageRef'
      responses:
        '200':
          description: Success
          schema:
            properties:
              response:
                items:
                  $ref: '#/definitions/CarLicensePlateResponse'
                type: array
            type: object
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  CarLicensePlateResponse:
    properties:
      confidence:
        type: number
      coordinate:
        $ref: '#/definitions/TransformerBox'
      label:
        type: string
      value:
        type: string
    type: object
  Error:
    properties:
      code:
        type: integer
      message:
        type: string
    required:
      - code
      - message
    type: object
  ImageRef:
    properties:
      Bytes:
        description: Base64 encoded image. Only one of Bytes or URL should be specified
        type: string
      URL:
        description: URI of image. Only one of Bytes or URL should be specified
        type: string
    type: object
  TransformerBox:
    properties:
      xmax:
        type: integer
      xmin:
        type: integer
      ymax:
        type: integer
      ymin:
        type: integer
    type: object
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
security:
  - BearerAuth: []
x-components: {}

