swagger: '2.0'
info:
  title: Tiyaro
  version: '1.0'
host: api.tiyaro.ai
basePath: /
schemes:
  - https
paths:
  /model_specific_path:
    parameters:
      - description: 'Available service tiers: [cpuflex(default), gpuflex]'
        in: query
        name: serviceTier
        required: false
        type: string
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/NLPQandA'
      responses:
        '200':
          description: Success
          schema:
            properties:
              response:
                $ref: '#/definitions/QuestionAnswerResponse'
            type: object
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    properties:
      code:
        type: integer
      message:
        type: string
    required:
      - code
      - message
    type: object
  NLPQandA:
    properties:
      context:
        type: string
      question:
        type: string
    required:
      - context
      - question
    type: object
  QuestionAnswerResponse:
    properties:
      answer:
        type: string
      end:
        type: integer
      score:
        type: number
      start:
        type: integer
    type: object
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
security:
  - BearerAuth: []
x-components: {}

