swagger: '2.0'
info:
  title: Tiyaro
  version: '1.0'
host: api.tiyaro.ai
basePath: /
schemes:
  - https
paths:
  /model_specific_path:
    parameters:
      - description: 'Available service tiers: [cpuflex(default), gpuflex]'
        in: query
        name: serviceTier
        required: false
        type: string
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/RekognitionDetectProtectiveEquipmentParam'
      responses:
        '200':
          description: Success
          schema:
            properties:
              response:
                $ref: '#/definitions/RekognitionEquipmentResponse'
            type: object
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    properties:
      code:
        type: integer
      message:
        type: string
    required:
      - code
      - message
    type: object
  ImageRef:
    properties:
      Bytes:
        description: Base64 encoded image. Only one of Bytes or URL should be specified
        type: string
      URL:
        description: URI of image. Only one of Bytes or URL should be specified
        type: string
    type: object
  RekognitionBodyPart:
    properties:
      Confidence:
        type: number
      EquipmentDetections:
        items:
          $ref: '#/definitions/RekognitionEquipmentDetection'
        type: array
      Name:
        type: string
    type: object
  RekognitionBoundingBox:
    properties:
      Height:
        type: number
      Left:
        type: number
      Top:
        type: number
      Width:
        type: number
    type: object
  RekognitionConfidenceValue:
    properties:
      Confidence:
        type: number
      Value:
        type: boolean
    type: object
  RekognitionDetectProtectiveEquipmentParam:
    properties:
      Image:
        $ref: '#/definitions/ImageRef'
      SummarizationAttributes:
        $ref: '#/definitions/SummarizationAttributes'
    required:
      - Image
    type: object
  RekognitionEquimentPerson:
    properties:
      BodyParts:
        items:
          $ref: '#/definitions/RekognitionBodyPart'
        type: array
      BoundingBox:
        $ref: '#/definitions/RekognitionBoundingBox'
      Confidence:
        type: number
      Id:
        type: number
    type: object
  RekognitionEquipmentDetection:
    properties:
      BoundingBox:
        $ref: '#/definitions/RekognitionBoundingBox'
      Confidence:
        type: number
      CoversBodyPart:
        $ref: '#/definitions/RekognitionConfidenceValue'
      Type:
        type: string
    type: object
  RekognitionEquipmentResponse:
    properties:
      Persons:
        items:
          $ref: '#/definitions/RekognitionEquimentPerson'
        type: array
      ProtectiveEquipmentModelVersion:
        type: string
      Summary:
        $ref: '#/definitions/RekognitionEquipmentSummary'
    type: object
  RekognitionEquipmentSummary:
    properties:
      PersonsIndeterminate:
        items:
          type: number
        type: array
      PersonsWithRequiredEquipment:
        items:
          type: number
        type: array
      PersonsWithoutRequiredEquipment:
        items:
          type: number
        type: array
    type: object
  SummarizationAttributes:
    properties:
      MinConfidence:
        type: number
      RequiredEquipmentTypes:
        items:
          type: string
        type: array
    type: object
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
security:
  - BearerAuth: []
x-components: {}

