swagger: '2.0'
info:
  title: Tiyaro
  version: '1.0'
host: api.tiyaro.ai
basePath: /
schemes:
  - https
paths:
  /model_specific_path:
    parameters:
      - description: 'Available service tiers: [cpuflex(default), gpuflex]'
        in: query
        name: serviceTier
        required: false
        type: string
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/RekognitionDetectModerationLabelsParam'
      responses:
        '200':
          description: Success
          schema:
            properties:
              response:
                $ref: '#/definitions/RekognitionModerationResponse'
            type: object
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  ContentClassifiersObject:
    properties:
      ContentClassifiers:
        items:
          type: string
        type: array
    type: object
  Error:
    properties:
      code:
        type: integer
      message:
        type: string
    required:
      - code
      - message
    type: object
  HumanLoopConfig:
    properties:
      DataAttributes:
        $ref: '#/definitions/ContentClassifiersObject'
      FlowDefitinitionArn:
        type: string
      HumanLoopName:
        type: string
    type: object
  ImageRef:
    properties:
      Bytes:
        description: Base64 encoded image. Only one of Bytes or URL should be specified
        type: string
      URL:
        description: URI of image. Only one of Bytes or URL should be specified
        type: string
    type: object
  RekognitionDetectModerationLabelsParam:
    properties:
      HumanLoopConfig:
        $ref: '#/definitions/HumanLoopConfig'
      Image:
        $ref: '#/definitions/ImageRef'
      MinConfidence:
        type: number
    required:
      - Image
    type: object
  RekognitionHumanActivationOutput:
    properties:
      HumanLoopActivationConditionsEvaluationResults:
        type: string
      HumanLoopActivationReasons:
        items:
          type: string
        type: array
      HumanLoopArn:
        type: string
    type: object
  RekognitionModerationLabel:
    properties:
      Confidence:
        type: number
      Name:
        type: string
      ParentName:
        type: string
    type: object
  RekognitionModerationResponse:
    properties:
      HumanLoopActivationOutput:
        $ref: '#/definitions/RekognitionHumanActivationOutput'
      ModerationLabels:
        items:
          $ref: '#/definitions/RekognitionModerationLabel'
        type: array
      ModerationModelVersion:
        type: string
    type: object
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
security:
  - BearerAuth: []
x-components: {}

