swagger: '2.0'
info:
  title: Tiyaro
  version: '1.0'
host: api.tiyaro.ai
basePath: /
schemes:
  - https
paths:
  /model_specific_path:
    parameters:
      - description: 'Available service tiers: [cpuflex(default), gpuflex]'
        in: query
        name: serviceTier
        required: false
        type: string
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/NLPZeroShotClassification'
      responses:
        '200':
          description: Success
          schema:
            properties:
              response:
                items:
                  $ref: '#/definitions/ZeroShotResponse'
                type: array
            type: object
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    properties:
      code:
        type: integer
      message:
        type: string
    required:
      - code
      - message
    type: object
  NLPZeroShotClassification:
    properties:
      input:
        type: string
      labels:
        items:
          type: string
        type: array
      multiLabel:
        description: Whether multiple candidate labels can be true. Default False
        type: boolean
    required:
      - input
      - labels
    type: object
  ZeroShotResponse:
    properties:
      labels:
        items:
          type: string
        type: array
      scores:
        items:
          type: number
        type: array
      sequence:
        type: string
      warnings:
        items:
          type: string
        type: array
    type: object
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
security:
  - BearerAuth: []
x-components: {}

